### ISSUE TITLE
Deploy fails : Buffers are not supported

### ISSUE THREAD

**Issue by Fanaen** [zhevron/gulp-deploy-git#5]
When using `gulp-deploy-git` with the default task desploy, an `Error: Buffers are not supported` occured in the gulp workflow. I'm trying to run the tool in the following environment:
- Windows 10
- node v5.7.0
- npm v3.8.0
- gulp ^3.9.1
- gulp-deploy-git ^0.5.3

The corresponding gulpfile.js:

``` javascript
var gulp = require('gulp');
var deploy = require('gulp-deploy-git');

gulp.task('deploy', function() {
  return gulp.src('dist/**/*')
    .pipe(deploy({
      repository: 'http://gitlab.example.com:20000/username/gdg-test.git',
      verbose: true,
      debug: true
    }));
});
```

And the result:

``` shell
C:\Users\Elouan\Labo\gdg-test>gulp deploy
[10:23:02] Using gulpfile ~\Labo\gdg-test\gulpfile.js
[10:23:02] Starting 'deploy'...
[10:23:02] 'deploy' errored after 18 ms
[10:23:02] Error: Buffers are not supported
    at formatError (C:\Users\Elouan\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Elouan\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\Elouan\Labo\gdg-test\node_modules\orchestrator\index.js:264:8)
    at C:\Users\Elouan\Labo\gdg-test\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\Elouan\Labo\gdg-test\node_modules\orchestrator\lib\runTask.js:21:8)
    at DestroyableTransform.<anonymous> (C:\Users\Elouan\Labo\gdg-test\node_modules\orchestrator\lib\runTask.js:52:4)
    at DestroyableTransform.f (C:\Users\Elouan\Labo\gdg-test\node_modules\once\once.js:17:25)
    at emitOne (events.js:95:20)
```

Is that the error mentionned in the README?

**Comment by zhevron** [comment]
My bad, documentation forgot the `{ read: false }` argument to `gulp.src`

The correct task should be:

``` js
var gulp = require('gulp');
var deploy = require('gulp-deploy-git');

gulp.task('deploy', function() {
  return gulp.src('dist/**/*', { read: false })
    .pipe(deploy({
      repository: 'http://gitlab.example.com:20000/username/gdg-test.git',
      verbose: true,
      debug: true
    }));
});
```

**Comment by Fanaen** [comment]
This solves the issue. Thanks for the quick answer!
